name: Workflow CI - Iris SVM

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mlflow scikit-learn pandas

      - name: Run MLProject (Re-training)
        run: |
          cd MLProject
          mlflow run . --no-conda
          
      - name: Simpan Artefak ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-artifacts
          path: MLProject/mlruns/

      # Ambil RUN_ID menggunakan Python
      - name: Get latest MLflow run_id
        working-directory: MLProject
        shell: python
        run: |
          import mlflow
          import os
          runs = mlflow.search_runs(experiment_ids=["0"], max_results=1, order_by=["attributes.start_time DESC"])
          
          if not runs.empty:
              run_id = runs.iloc[0]["run_id"]
              with open(os.environ['GITHUB_ENV'], 'a') as f:
                  f.write(f"RUN_ID={run_id}\n")
              print(f"Successfully found Run ID: {run_id}")
          else:
              print("No runs found in MLflow tracking!")
              exit(1)

      # Build Docker menggunakan Virtual Environment bersih
      - name: Build Docker Image
        run: |
          cd MLProject
          
          python -m venv clean_env
          clean_env/bin/python -m pip install mlflow "docker>=7.1.0" "requests>=2.32.2" urllib3
          
          echo "Menggunakan RUN_ID: ${{ env.RUN_ID }}"
          
          clean_env/bin/python -m mlflow models build-docker -m mlruns/0/${{ env.RUN_ID }}/artifacts/svm_model -n ${{ secrets.DOCKERHUB_USERNAME }}/iris-svm-model:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Image ke Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/iris-svm-model:latest