name: Workflow CI - Iris SVM

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Setup Python 3.10 (Versi paling stabil untuk menghindari bug Docker MLflow)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 2. Install semua library yang dibutuhkan sesuai saran penguji (MLflow 2.19.0)
      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy matplotlib seaborn dagshub

      # 3. Hapus cache model lama & Lakukan Training Model Ulang
      - name: Run MLProject (Re-training)
        run: |
          cd MLProject
          rm -rf mlruns/
          mlflow run . --env-manager=local
          
      # 4. Simpan Artefak ke GitHub (pakai v4 sesuai aturan baru)
      - name: Simpan Artefak ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-artifacts
          path: MLProject/mlruns/

      # 5. Ambil RUN_ID model yang BARU SAJA ditraining (mencari di semua eksperimen)
      - name: Get latest MLflow run_id
        working-directory: MLProject
        shell: python
        run: |
          import mlflow
          import os
          
          experiments = mlflow.search_experiments()
          all_exp_ids = [exp.experiment_id for exp in experiments]
          
          runs = mlflow.search_runs(experiment_ids=all_exp_ids, max_results=1, order_by=["attributes.start_time DESC"])
          
          if not runs.empty:
              run_id = runs.iloc[0]["run_id"]
              exp_id = runs.iloc[0]["experiment_id"]
              with open(os.environ['GITHUB_ENV'], 'a') as f:
                  f.write(f"RUN_ID={run_id}\n")
                  f.write(f"EXP_ID={exp_id}\n")
              print(f"Successfully found Run ID: {run_id} in Experiment: {exp_id}")
          else:
              print("No runs found in MLflow tracking!")
              exit(1)

      # 6. Build Docker Image (Pakai ruang isolasi Venv agar terhindar dari bug bawaan Ubuntu)
      - name: Build Docker Image
        run: |
          cd MLProject
          
          python -m venv clean_env
          clean_env/bin/python -m pip install mlflow==2.19.0 "docker>=7.1.0" "requests>=2.32.2" urllib3
          
          clean_env/bin/python -m mlflow models build-docker -m mlruns/${{ env.EXP_ID }}/${{ env.RUN_ID }}/artifacts/svm_model -n ${{ secrets.DOCKER_USERNAME }}/iris-svm-model:latest

      # 7. Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Push Image ke Docker Hub
      - name: Push Image ke Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/iris-svm-model:latest