name: Workflow CI - Iris SVM

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies & Fix error Docker URL scheme
      - name: Install Dependencies
        run: |
          pip install mlflow scikit-learn pandas "requests<2.32.0" "urllib3<2" docker

      # 1. Melakukan Re-training menggunakan MLflow Project
      - name: Run MLProject (Re-training)
        run: |
          cd Workflow-CI/MLProject
          mlflow run . --no-conda
          
      # 2. Upload Artefak (Menyimpan artefak ke GitHub Repository)
      - name: Simpan Artefak ke GitHub
        uses: actions/upload-artifact@v3
        with:
          name: mlruns-artifacts
          path: Workflow-CI/MLProject/mlruns/

      # 3. Build Docker Image dengan mlflow build-docker
      - name: Build Docker Image
        run: |
          cd Workflow-CI/MLProject
          # Mengambil Run ID terbaru secara dinamis (mengabaikan meta.yaml)
          RUN_ID=$(ls -t mlruns/0 | grep -v meta.yaml | head -n 1)
          echo "Menggunakan RUN_ID: $RUN_ID"
          
          # Membangun docker image dari model MLflow
          mlflow models build-docker -m mlruns/0/$RUN_ID/artifacts/svm_model -n ${{ secrets.DOCKERHUB_USERNAME }}/iris-svm-model:latest

      # 4. Login ke Docker Hub & Push
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Image ke Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/iris-svm-model:latest